name: SpellCraft
version: '${project.version}'
main: com.spellcraft.SpellCraftPlugin
api-version: '1.20'
folia-supported: true
soft-depend: [WorldGuard, GriefPrevention]
author: Hihelloy
description: A comprehensive magic based spell system for Minecraft

libraries:
  - net.kyori:adventure-api:4.26.1
  - net.kyori:adventure-platform-bukkit:4.4.1

commands:
  spell:
    description: Main SpellCraft command
    usage: /<command> <subcommand>
    aliases: [sc,spells,s]
    permission: spellcraft.command.spell

  spellbook:
    description: SpellBook management command
    usage: /<command> <create|give> [player] [spell]
    permission: spellcraft.command.spellbook

  spellbind:
    description: Bind a spell to a slot
    usage: /<command> <slot> <spell>
    permission: spellcraft.command.spellbind

  house:
    description: Choose your magical house
    usage: /<command> <choose> [house]
    permission: spellcraft.command.house

permissions:

  spellcraft.command.spell:
    default: true

  spellcraft.command.spellbind:
    default: true

  spellcraft.command.house:
    default: true

  spellcraft.command.spellbook:
    default: op

  spellcraft.spell.cast:
    default: true

  spellcraft.spell.*:
    default: true

  spellcraft.element.*:
    default: true

  spellcraft.house.*:
    default: true

  spellcraft.spellbook.use:
    default: true

  spellcraft.spellbook.craft:
    default: true

  spellcraft.spellbook.give:
    default: op

  spellcraft.admin.*:
    default: op
